# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlp_app', '0002_remove_photo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wlp_app.Location'),
            preserve_default=False,
        ),
    ]
