# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlp_app', '0003_photo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_taken',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
