# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wlp_app', '0004_photo_photo_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='location',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
