# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlp_app', '0006_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_taken',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='wildlifephotos/%Y/%m/%d', width_field='width_field'),
        ),
    ]
